name: contextualize
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.5
  - pymssql
  - spacy
  - pip:
    - gunicorn
    - meinheld
    - waitress
    - hug
    - hug_middleware_cors
    - en_core_web_sm
